// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUMtjvF910TpW44k1d8PuxcxbcAK3tlvs',
    appId: '1:151056945688:web:cbb292bb9b5221b258e96d',
    messagingSenderId: '151056945688',
    projectId: 'iiatimd-skyrim-app',
    authDomain: 'iiatimd-skyrim-app.firebaseapp.com',
    storageBucket: 'iiatimd-skyrim-app.appspot.com',
    measurementId: 'G-YBXBH5JBP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbgHsuQTSDgMv88bAD6cI_JUNs2_ioPxw',
    appId: '1:151056945688:android:87dd9ceb1be80a0058e96d',
    messagingSenderId: '151056945688',
    projectId: 'iiatimd-skyrim-app',
    storageBucket: 'iiatimd-skyrim-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_nu6qvEtfeh971YmBPcL47xDPLCf6Gs',
    appId: '1:151056945688:ios:a3cda3a24ab8144a58e96d',
    messagingSenderId: '151056945688',
    projectId: 'iiatimd-skyrim-app',
    storageBucket: 'iiatimd-skyrim-app.appspot.com',
    iosClientId: '151056945688-3fcfgq2rmvi4kf5ud4iin6l2vv3gnrrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.iiatimdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_nu6qvEtfeh971YmBPcL47xDPLCf6Gs',
    appId: '1:151056945688:ios:ddd19c86ed63542158e96d',
    messagingSenderId: '151056945688',
    projectId: 'iiatimd-skyrim-app',
    storageBucket: 'iiatimd-skyrim-app.appspot.com',
    iosClientId: '151056945688-kq5mcin15nqaspocqugmu3iekoeas865.apps.googleusercontent.com',
    iosBundleId: 'com.example.iiatimdApp.RunnerTests',
  );
}
